# Generated by Django 4.1.7 on 2023-03-04 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "Date",
                    models.DateField(primary_key=True, serialize=False, unique=True),
                ),
                ("Course", models.JSONField(blank=True, default=list)),
                (
                    "Vistors_list",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
