# Generated by Django 4.1.7 on 2023-03-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
