# Generated by Django 4.1.7 on 2023-03-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
