# Generated by Django 4.1.7 on 2023-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="Course",
        ),
        migrations.AddField(
            model_name="menu",
            name="item1",
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name="menu",
            name="item2",
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name="menu",
            name="item3",
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name="menu",
            name="item4",
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name="menu",
            name="item5",
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
